# Generated by Django 3.1.1 on 2020-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('issue', models.CharField(max_length=25)),
                ('publication_date', models.CharField(max_length=100)),
                ('cover_url', models.TextField()),
                ('personal_image', models.ImageField(upload_to='images/')),
                ('notes', models.TextField()),
            ],
        ),
    ]
