# Generated by Django 3.1.1 on 2020-09-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='personal_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
